// Paulo Henrique

export const buttonsUtils = {
    1: {
      text: "Sair",
      bg: "red.500",
      color: "white",
      colorScheme: "red",
      onClick: (e: unknown) => {localStorage.removeItem("token"); localStorage.removeItem("email"); window.location.href = "/"},
    },
    2: {
      text: "Salvar",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Salvar"),
    },
    3: {
        text: "Cancelar",
        bg: "gray.500",
        color: "white",
        colorScheme: "gray",
        onClick: () => alert("Você clicou no botão Cancelar"),
    },
    4: {
      text: "Cadastrar",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Cadastrar"),
    },
    5: {
      text: "Entrar com Google",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Entrar com Google"),
    },
    6: {
      text: "Prosseguir",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Prosseguir"),
    },
    7: {
      text: "Voltar",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => window.history.back(),
    },
    8: {
      text: "Enviar",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Enviar"),
    },
    9: {
      text: "Entrar",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Entrar"),
    },
    10: {
      text: "Adicionar",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: null,
    },
    11: {
      text: "Login",
      bg: "orange.900",
      color: "white",
      colorScheme: "orange",
      onClick: () => window.location.href = "/login",
    },
    12: {
      text: "Cadastro",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => window.location.href = "/cadastro/cliente",
    },
    13: {
      text: "Sim",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Sim"),
    },
    14: {
      text: "Não",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Não"),
    },
    15: {
      text: "Finalizar Compra",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Finalizar Compra"),
    },
    16: {
      text: "Dashboard",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => window.location.href = "/admin/dashboard",
    },
    17: {
      text: "Descartar Alterações",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Descartar Alterações"),
    },
    18: {
      text: "Adicionar",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Adicionar"),
    },
    19: {
      text: "Comprar Novamente",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Comprar Novamente"),
    },
    20: {
      text: "Visitar Loja",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Visitar Loja"),
    },
    21: {
      text: "+ Novo Produto",
      bg: "orange.900",
      color: "white",
      colorScheme: "orange",
      onClick: null,
    },
    22: {
      text: "Virar Produtor",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: null,
    },
    23: {
      text: "Cancelar Plano",
      bg: "red.400",
      color: "white",
      colorScheme: "red",
      onClick: null,
    },
  }