// Paulo Henrique

export const buttonsUtils = {
    1: {
      text: "Sair",
      bg: "red.500",
      color: "white",
      colorScheme: "red",
      onClick: () => alert("Você clicou no botão Sair"),
    },
    2: {
      text: "Salvar",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Salvar"),
    },
    3: {
        text: "Cancelar",
        bg: "gray.500",
        color: "white",
        colorScheme: "gray",
        onClick: () => alert("Você clicou no botão Cancelar"),
    },
    4: {
      text: "Cadastrar",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Cadastrar"),
    },
    5: {
      text: "Entrar com Google",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Entrar com Google"),
    },
    6: {
      text: "Prosseguir",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Prosseguir"),
    },
    7: {
      text: "Voltar",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Voltar"),
    },
    8: {
      text: "Enviar",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Enviar"),
    },
    9: {
      text: "Entrar",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Entrar"),
    },
    10: {
      text: "Comprar",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Comprar"),
    },
    11: {
      text: "Login",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Login"),
    },
    12: {
      text: "Cadastro",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Cadastro"),
    },
    13: {
      text: "Sim",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Sim"),
    },
    14: {
      text: "Não",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Não"),
    },
    15: {
      text: "Finalizar Compra",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Finalizar Compra"),
    },
    16: {
      text: "+ Seguir",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão + Seguir"),
    },
    17: {
      text: "Descartar Alterações",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Descartar Alterações"),
    },
    18: {
      text: "Adicionar",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Adicionar"),
    },
    19: {
      text: "Comprar Novamente",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Comprar Novamente"),
    },
    20: {
      text: "Visitar Loja",
      bg: "green.500",
      color: "white",
      colorScheme: "green",
      onClick: () => alert("Você clicou no botão Visitar Loja"),
    },
  }